print('Hallo wereld!')
print('het begin is meestal niet makkelijk')
naam = input('je naam aub. ')
print('aaah jij bent ',naam)
achteruit =''.join(reversed(naam))
print('Ooow achterstevoren heet je dan ',achteruit)
